version: '2.3'

networks:
  tanner_local:
    external: true
services:

# Snare service
  snare:
    build: .
    container_name: snare
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    ports:
     - "80:80"
    image: "mushorg/snare:latest"
